'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cama_Paciente
    Public Property idCama As Integer
    Public Property DPI As Integer
    Public Property fecha As Date

    Public Overridable Property Cama As Cama
    Public Overridable Property Paciente As Paciente

End Class
