'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cama
    Public Property idCama As Integer
    Public Property idPlanta As Integer
    Public Property estado As Boolean

    Public Overridable Property Planta As Planta
    Public Overridable Property Cama_Paciente As ICollection(Of Cama_Paciente) = New HashSet(Of Cama_Paciente)

End Class
