'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Diagnostico
    Public Property codigoDiagnostico As Integer
    Public Property descripcion As String

    Public Overridable Property Diagnostico_Paciente As ICollection(Of Diagnostico_Paciente) = New HashSet(Of Diagnostico_Paciente)
    Public Overridable Property Medico As ICollection(Of Medico) = New HashSet(Of Medico)

End Class
