'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Medico
    Public Property codigoMedico As Integer
    Public Property nombre As String
    Public Property apellido As String

    Public Overridable Property Medico_Paciente As ICollection(Of Medico_Paciente) = New HashSet(Of Medico_Paciente)
    Public Overridable Property Diagnostico As ICollection(Of Diagnostico) = New HashSet(Of Diagnostico)

End Class
