'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Paciente
    Public Property DPI As Integer
    Public Property noIGSS As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property fechaNacimiento As Date

    Public Overridable Property Cama_Paciente As ICollection(Of Cama_Paciente) = New HashSet(Of Cama_Paciente)
    Public Overridable Property Diagnostico_Paciente As ICollection(Of Diagnostico_Paciente) = New HashSet(Of Diagnostico_Paciente)
    Public Overridable Property Medico_Paciente As ICollection(Of Medico_Paciente) = New HashSet(Of Medico_Paciente)
    Public Overridable Property TarjetaVisita As ICollection(Of TarjetaVisita) = New HashSet(Of TarjetaVisita)

End Class
