'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbHospitalEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbHospitalEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Cama() As DbSet(Of Cama)
    Public Property Cama_Paciente() As DbSet(Of Cama_Paciente)
    Public Property Diagnostico() As DbSet(Of Diagnostico)
    Public Property Diagnostico_Paciente() As DbSet(Of Diagnostico_Paciente)
    Public Property Medico() As DbSet(Of Medico)
    Public Property Medico_Paciente() As DbSet(Of Medico_Paciente)
    Public Property Paciente() As DbSet(Of Paciente)
    Public Property Planta() As DbSet(Of Planta)
    Public Property TarjetaVisita() As DbSet(Of TarjetaVisita)

End Class
