
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("d10c80a0-8850-4d37-863c-abf6b5ede69f")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Cama__idPlanta__1BFD2C07", "Planta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Planta), "Cama", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Cama), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Cama_Paci__idCam__1ED998B2", "Cama", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Cama), "Cama_Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Cama_Paciente), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Cama_Pacien__DPI__1FCDBCEB", "Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Paciente), "Cama_Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Cama_Paciente), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Diagnosti__codig__267ABA7A", "Diagnostico", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Diagnostico), "Diagnostico_Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Diagnostico_Paciente), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Diagnostico__DPI__25869641", "Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Paciente), "Diagnostico_Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Diagnostico_Paciente), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Medico_Pa__codig__29572725", "Medico", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Medico), "Medico_Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Medico_Paciente), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__Medico_Paci__DPI__2A4B4B5E", "Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Paciente), "Medico_Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Medico_Paciente), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "FK__TarjetaVisi__DPI__22AA2996", "Paciente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SH.BusinessObjects.Models.Paciente), "TarjetaVisita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.TarjetaVisita), True)>
<Assembly: EdmRelationshipAttribute("SH.BusinessObjects.Models", "Diagnostico_Medico", "Medico", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Medico), "Diagnostico", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SH.BusinessObjects.Models.Diagnostico))>

#End Region

Namespace SH.BusinessObjects.Models

    #Region "Contextos"
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public Partial Class dbHospitalEntities
        Inherits ObjectContext
    
        #Region "Constructores"
    
        ''' <summary>
        ''' Inicializa un nuevo objeto dbHospitalEntities usando la cadena de conexión encontrada en la sección 'dbHospitalEntities' del archivo de configuración de la aplicación.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=dbHospitalEntities", "dbHospitalEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Inicializar un nuevo objeto dbHospitalEntities.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "dbHospitalEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Inicializar un nuevo objeto dbHospitalEntities.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "dbHospitalEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Métodos parciales"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Propiedades de ObjectSet"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Cama() As ObjectSet(Of Cama)
            Get
                If (_Cama Is Nothing) Then
                    _Cama = MyBase.CreateObjectSet(Of Cama)("Cama")
                End If
                Return _Cama
            End Get
        End Property
    
        Private _Cama As ObjectSet(Of Cama)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Cama_Paciente() As ObjectSet(Of Cama_Paciente)
            Get
                If (_Cama_Paciente Is Nothing) Then
                    _Cama_Paciente = MyBase.CreateObjectSet(Of Cama_Paciente)("Cama_Paciente")
                End If
                Return _Cama_Paciente
            End Get
        End Property
    
        Private _Cama_Paciente As ObjectSet(Of Cama_Paciente)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Diagnostico() As ObjectSet(Of Diagnostico)
            Get
                If (_Diagnostico Is Nothing) Then
                    _Diagnostico = MyBase.CreateObjectSet(Of Diagnostico)("Diagnostico")
                End If
                Return _Diagnostico
            End Get
        End Property
    
        Private _Diagnostico As ObjectSet(Of Diagnostico)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Diagnostico_Paciente() As ObjectSet(Of Diagnostico_Paciente)
            Get
                If (_Diagnostico_Paciente Is Nothing) Then
                    _Diagnostico_Paciente = MyBase.CreateObjectSet(Of Diagnostico_Paciente)("Diagnostico_Paciente")
                End If
                Return _Diagnostico_Paciente
            End Get
        End Property
    
        Private _Diagnostico_Paciente As ObjectSet(Of Diagnostico_Paciente)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Medico() As ObjectSet(Of Medico)
            Get
                If (_Medico Is Nothing) Then
                    _Medico = MyBase.CreateObjectSet(Of Medico)("Medico")
                End If
                Return _Medico
            End Get
        End Property
    
        Private _Medico As ObjectSet(Of Medico)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Medico_Paciente() As ObjectSet(Of Medico_Paciente)
            Get
                If (_Medico_Paciente Is Nothing) Then
                    _Medico_Paciente = MyBase.CreateObjectSet(Of Medico_Paciente)("Medico_Paciente")
                End If
                Return _Medico_Paciente
            End Get
        End Property
    
        Private _Medico_Paciente As ObjectSet(Of Medico_Paciente)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Paciente() As ObjectSet(Of Paciente)
            Get
                If (_Paciente Is Nothing) Then
                    _Paciente = MyBase.CreateObjectSet(Of Paciente)("Paciente")
                End If
                Return _Paciente
            End Get
        End Property
    
        Private _Paciente As ObjectSet(Of Paciente)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property Planta() As ObjectSet(Of Planta)
            Get
                If (_Planta Is Nothing) Then
                    _Planta = MyBase.CreateObjectSet(Of Planta)("Planta")
                End If
                Return _Planta
            End Get
        End Property
    
        Private _Planta As ObjectSet(Of Planta)
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        Public ReadOnly Property TarjetaVisita() As ObjectSet(Of TarjetaVisita)
            Get
                If (_TarjetaVisita Is Nothing) Then
                    _TarjetaVisita = MyBase.CreateObjectSet(Of TarjetaVisita)("TarjetaVisita")
                End If
                Return _TarjetaVisita
            End Get
        End Property
    
        Private _TarjetaVisita As ObjectSet(Of TarjetaVisita)

        #End Region

        #Region "Métodos AddTo"
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Cama. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToCama(ByVal cama As Cama)
            MyBase.AddObject("Cama", cama)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Cama_Paciente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToCama_Paciente(ByVal cama_Paciente As Cama_Paciente)
            MyBase.AddObject("Cama_Paciente", cama_Paciente)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Diagnostico. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToDiagnostico(ByVal diagnostico As Diagnostico)
            MyBase.AddObject("Diagnostico", diagnostico)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Diagnostico_Paciente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToDiagnostico_Paciente(ByVal diagnostico_Paciente As Diagnostico_Paciente)
            MyBase.AddObject("Diagnostico_Paciente", diagnostico_Paciente)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Medico. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToMedico(ByVal medico As Medico)
            MyBase.AddObject("Medico", medico)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Medico_Paciente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToMedico_Paciente(ByVal medico_Paciente As Medico_Paciente)
            MyBase.AddObject("Medico_Paciente", medico_Paciente)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Paciente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToPaciente(ByVal paciente As Paciente)
            MyBase.AddObject("Paciente", paciente)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet Planta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToPlanta(ByVal planta As Planta)
            MyBase.AddObject("Planta", planta)
        End Sub
    
        ''' <summary>
        ''' Método desusado para agregar un nuevo objeto al EntitySet TarjetaVisita. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
        ''' </summary>
        Public Sub AddToTarjetaVisita(ByVal tarjetaVisita As TarjetaVisita)
            MyBase.AddObject("TarjetaVisita", tarjetaVisita)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entidades"
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Cama")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Cama
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Cama.
        ''' </summary>
        ''' <param name="idCama">Valor inicial de la propiedad idCama.</param>
        ''' <param name="idPlanta">Valor inicial de la propiedad idPlanta.</param>
        ''' <param name="estado">Valor inicial de la propiedad estado.</param>
        Public Shared Function CreateCama(idCama As Global.System.Int32, idPlanta As Global.System.Int32, estado As Global.System.Boolean) As Cama
            Dim cama as Cama = New Cama
            cama.idCama = idCama
            cama.idPlanta = idPlanta
            cama.estado = estado
            Return cama
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property idCama() As Global.System.Int32
            Get
                Return _idCama
            End Get
            Set
                If (_idCama <> Value) Then
                    OnidCamaChanging(value)
                    ReportPropertyChanging("idCama")
                    _idCama = StructuralObject.SetValidValue(value, "idCama")
                    ReportPropertyChanged("idCama")
                    OnidCamaChanged()
                End If
            End Set
        End Property
    
        Private _idCama As Global.System.Int32
        Private Partial Sub OnidCamaChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnidCamaChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property idPlanta() As Global.System.Int32
            Get
                Return _idPlanta
            End Get
            Set
                OnidPlantaChanging(value)
                ReportPropertyChanging("idPlanta")
                _idPlanta = StructuralObject.SetValidValue(value, "idPlanta")
                ReportPropertyChanged("idPlanta")
                OnidPlantaChanged()
            End Set
        End Property
    
        Private _idPlanta As Global.System.Int32
        Private Partial Sub OnidPlantaChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnidPlantaChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property estado() As Global.System.Boolean
            Get
                Return _estado
            End Get
            Set
                OnestadoChanging(value)
                ReportPropertyChanging("estado")
                _estado = StructuralObject.SetValidValue(value, "estado")
                ReportPropertyChanged("estado")
                OnestadoChanged()
            End Set
        End Property
    
        Private _estado As Global.System.Boolean
        Private Partial Sub OnestadoChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnestadoChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Cama__idPlanta__1BFD2C07", "Planta")>
        Public Property Planta() As Planta
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Planta)("SH.BusinessObjects.Models.FK__Cama__idPlanta__1BFD2C07", "Planta").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Planta)("SH.BusinessObjects.Models.FK__Cama__idPlanta__1BFD2C07", "Planta").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property PlantaReference() As EntityReference(Of Planta)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Planta)("SH.BusinessObjects.Models.FK__Cama__idPlanta__1BFD2C07", "Planta")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Planta)("SH.BusinessObjects.Models.FK__Cama__idPlanta__1BFD2C07", "Planta", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Cama_Paci__idCam__1ED998B2", "Cama_Paciente")>
         Public Property Cama_Paciente() As EntityCollection(Of Cama_Paciente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Cama_Paciente)("SH.BusinessObjects.Models.FK__Cama_Paci__idCam__1ED998B2", "Cama_Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Cama_Paciente)("SH.BusinessObjects.Models.FK__Cama_Paci__idCam__1ED998B2", "Cama_Paciente", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Cama_Paciente")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Cama_Paciente
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Cama_Paciente.
        ''' </summary>
        ''' <param name="idCama">Valor inicial de la propiedad idCama.</param>
        ''' <param name="dPI">Valor inicial de la propiedad DPI.</param>
        ''' <param name="fecha">Valor inicial de la propiedad fecha.</param>
        Public Shared Function CreateCama_Paciente(idCama As Global.System.Int32, dPI As Global.System.Int32, fecha As Global.System.DateTime) As Cama_Paciente
            Dim cama_Paciente as Cama_Paciente = New Cama_Paciente
            cama_Paciente.idCama = idCama
            cama_Paciente.DPI = dPI
            cama_Paciente.fecha = fecha
            Return cama_Paciente
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property idCama() As Global.System.Int32
            Get
                Return _idCama
            End Get
            Set
                If (_idCama <> Value) Then
                    OnidCamaChanging(value)
                    ReportPropertyChanging("idCama")
                    _idCama = StructuralObject.SetValidValue(value, "idCama")
                    ReportPropertyChanged("idCama")
                    OnidCamaChanged()
                End If
            End Set
        End Property
    
        Private _idCama As Global.System.Int32
        Private Partial Sub OnidCamaChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnidCamaChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property DPI() As Global.System.Int32
            Get
                Return _DPI
            End Get
            Set
                If (_DPI <> Value) Then
                    OnDPIChanging(value)
                    ReportPropertyChanging("DPI")
                    _DPI = StructuralObject.SetValidValue(value, "DPI")
                    ReportPropertyChanged("DPI")
                    OnDPIChanged()
                End If
            End Set
        End Property
    
        Private _DPI As Global.System.Int32
        Private Partial Sub OnDPIChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnDPIChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property fecha() As Global.System.DateTime
            Get
                Return _fecha
            End Get
            Set
                OnfechaChanging(value)
                ReportPropertyChanging("fecha")
                _fecha = StructuralObject.SetValidValue(value, "fecha")
                ReportPropertyChanged("fecha")
                OnfechaChanged()
            End Set
        End Property
    
        Private _fecha As Global.System.DateTime
        Private Partial Sub OnfechaChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnfechaChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Cama_Paci__idCam__1ED998B2", "Cama")>
        Public Property Cama() As Cama
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cama)("SH.BusinessObjects.Models.FK__Cama_Paci__idCam__1ED998B2", "Cama").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cama)("SH.BusinessObjects.Models.FK__Cama_Paci__idCam__1ED998B2", "Cama").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property CamaReference() As EntityReference(Of Cama)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cama)("SH.BusinessObjects.Models.FK__Cama_Paci__idCam__1ED998B2", "Cama")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Cama)("SH.BusinessObjects.Models.FK__Cama_Paci__idCam__1ED998B2", "Cama", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Cama_Pacien__DPI__1FCDBCEB", "Paciente")>
        Public Property Paciente() As Paciente
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Cama_Pacien__DPI__1FCDBCEB", "Paciente").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Cama_Pacien__DPI__1FCDBCEB", "Paciente").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property PacienteReference() As EntityReference(Of Paciente)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Cama_Pacien__DPI__1FCDBCEB", "Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Cama_Pacien__DPI__1FCDBCEB", "Paciente", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Diagnostico")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Diagnostico
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Diagnostico.
        ''' </summary>
        ''' <param name="codigoDiagnostico">Valor inicial de la propiedad codigoDiagnostico.</param>
        ''' <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        Public Shared Function CreateDiagnostico(codigoDiagnostico As Global.System.Int32, descripcion As Global.System.String) As Diagnostico
            Dim diagnostico as Diagnostico = New Diagnostico
            diagnostico.codigoDiagnostico = codigoDiagnostico
            diagnostico.descripcion = descripcion
            Return diagnostico
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property codigoDiagnostico() As Global.System.Int32
            Get
                Return _codigoDiagnostico
            End Get
            Set
                If (_codigoDiagnostico <> Value) Then
                    OncodigoDiagnosticoChanging(value)
                    ReportPropertyChanging("codigoDiagnostico")
                    _codigoDiagnostico = StructuralObject.SetValidValue(value, "codigoDiagnostico")
                    ReportPropertyChanged("codigoDiagnostico")
                    OncodigoDiagnosticoChanged()
                End If
            End Set
        End Property
    
        Private _codigoDiagnostico As Global.System.Int32
        Private Partial Sub OncodigoDiagnosticoChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OncodigoDiagnosticoChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property descripcion() As Global.System.String
            Get
                Return _descripcion
            End Get
            Set
                OndescripcionChanging(value)
                ReportPropertyChanging("descripcion")
                _descripcion = StructuralObject.SetValidValue(value, false, "descripcion")
                ReportPropertyChanged("descripcion")
                OndescripcionChanged()
            End Set
        End Property
    
        Private _descripcion As Global.System.String
        Private Partial Sub OndescripcionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OndescripcionChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Diagnosti__codig__267ABA7A", "Diagnostico_Paciente")>
         Public Property Diagnostico_Paciente() As EntityCollection(Of Diagnostico_Paciente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Diagnostico_Paciente)("SH.BusinessObjects.Models.FK__Diagnosti__codig__267ABA7A", "Diagnostico_Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Diagnostico_Paciente)("SH.BusinessObjects.Models.FK__Diagnosti__codig__267ABA7A", "Diagnostico_Paciente", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "Diagnostico_Medico", "Medico")>
         Public Property Medico() As EntityCollection(Of Medico)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Medico)("SH.BusinessObjects.Models.Diagnostico_Medico", "Medico")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Medico)("SH.BusinessObjects.Models.Diagnostico_Medico", "Medico", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Diagnostico_Paciente")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Diagnostico_Paciente
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Diagnostico_Paciente.
        ''' </summary>
        ''' <param name="codigoDiagnostico">Valor inicial de la propiedad codigoDiagnostico.</param>
        ''' <param name="dPI">Valor inicial de la propiedad DPI.</param>
        ''' <param name="fecha">Valor inicial de la propiedad fecha.</param>
        Public Shared Function CreateDiagnostico_Paciente(codigoDiagnostico As Global.System.Int32, dPI As Global.System.Int32, fecha As Global.System.DateTime) As Diagnostico_Paciente
            Dim diagnostico_Paciente as Diagnostico_Paciente = New Diagnostico_Paciente
            diagnostico_Paciente.codigoDiagnostico = codigoDiagnostico
            diagnostico_Paciente.DPI = dPI
            diagnostico_Paciente.fecha = fecha
            Return diagnostico_Paciente
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property codigoDiagnostico() As Global.System.Int32
            Get
                Return _codigoDiagnostico
            End Get
            Set
                If (_codigoDiagnostico <> Value) Then
                    OncodigoDiagnosticoChanging(value)
                    ReportPropertyChanging("codigoDiagnostico")
                    _codigoDiagnostico = StructuralObject.SetValidValue(value, "codigoDiagnostico")
                    ReportPropertyChanged("codigoDiagnostico")
                    OncodigoDiagnosticoChanged()
                End If
            End Set
        End Property
    
        Private _codigoDiagnostico As Global.System.Int32
        Private Partial Sub OncodigoDiagnosticoChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OncodigoDiagnosticoChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property DPI() As Global.System.Int32
            Get
                Return _DPI
            End Get
            Set
                If (_DPI <> Value) Then
                    OnDPIChanging(value)
                    ReportPropertyChanging("DPI")
                    _DPI = StructuralObject.SetValidValue(value, "DPI")
                    ReportPropertyChanged("DPI")
                    OnDPIChanged()
                End If
            End Set
        End Property
    
        Private _DPI As Global.System.Int32
        Private Partial Sub OnDPIChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnDPIChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property fecha() As Global.System.DateTime
            Get
                Return _fecha
            End Get
            Set
                OnfechaChanging(value)
                ReportPropertyChanging("fecha")
                _fecha = StructuralObject.SetValidValue(value, "fecha")
                ReportPropertyChanged("fecha")
                OnfechaChanged()
            End Set
        End Property
    
        Private _fecha As Global.System.DateTime
        Private Partial Sub OnfechaChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnfechaChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Diagnosti__codig__267ABA7A", "Diagnostico")>
        Public Property Diagnostico() As Diagnostico
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Diagnostico)("SH.BusinessObjects.Models.FK__Diagnosti__codig__267ABA7A", "Diagnostico").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Diagnostico)("SH.BusinessObjects.Models.FK__Diagnosti__codig__267ABA7A", "Diagnostico").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property DiagnosticoReference() As EntityReference(Of Diagnostico)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Diagnostico)("SH.BusinessObjects.Models.FK__Diagnosti__codig__267ABA7A", "Diagnostico")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Diagnostico)("SH.BusinessObjects.Models.FK__Diagnosti__codig__267ABA7A", "Diagnostico", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Diagnostico__DPI__25869641", "Paciente")>
        Public Property Paciente() As Paciente
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Diagnostico__DPI__25869641", "Paciente").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Diagnostico__DPI__25869641", "Paciente").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property PacienteReference() As EntityReference(Of Paciente)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Diagnostico__DPI__25869641", "Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Diagnostico__DPI__25869641", "Paciente", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Medico")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Medico
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Medico.
        ''' </summary>
        ''' <param name="codigoMedico">Valor inicial de la propiedad codigoMedico.</param>
        ''' <param name="nombre">Valor inicial de la propiedad nombre.</param>
        ''' <param name="apellido">Valor inicial de la propiedad apellido.</param>
        Public Shared Function CreateMedico(codigoMedico As Global.System.Int32, nombre As Global.System.String, apellido As Global.System.String) As Medico
            Dim medico as Medico = New Medico
            medico.codigoMedico = codigoMedico
            medico.nombre = nombre
            medico.apellido = apellido
            Return medico
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property codigoMedico() As Global.System.Int32
            Get
                Return _codigoMedico
            End Get
            Set
                If (_codigoMedico <> Value) Then
                    OncodigoMedicoChanging(value)
                    ReportPropertyChanging("codigoMedico")
                    _codigoMedico = StructuralObject.SetValidValue(value, "codigoMedico")
                    ReportPropertyChanged("codigoMedico")
                    OncodigoMedicoChanged()
                End If
            End Set
        End Property
    
        Private _codigoMedico As Global.System.Int32
        Private Partial Sub OncodigoMedicoChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OncodigoMedicoChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nombre() As Global.System.String
            Get
                Return _nombre
            End Get
            Set
                OnnombreChanging(value)
                ReportPropertyChanging("nombre")
                _nombre = StructuralObject.SetValidValue(value, false, "nombre")
                ReportPropertyChanged("nombre")
                OnnombreChanged()
            End Set
        End Property
    
        Private _nombre As Global.System.String
        Private Partial Sub OnnombreChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnombreChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property apellido() As Global.System.String
            Get
                Return _apellido
            End Get
            Set
                OnapellidoChanging(value)
                ReportPropertyChanging("apellido")
                _apellido = StructuralObject.SetValidValue(value, false, "apellido")
                ReportPropertyChanged("apellido")
                OnapellidoChanged()
            End Set
        End Property
    
        Private _apellido As Global.System.String
        Private Partial Sub OnapellidoChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnapellidoChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Medico_Pa__codig__29572725", "Medico_Paciente")>
         Public Property Medico_Paciente() As EntityCollection(Of Medico_Paciente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Medico_Paciente)("SH.BusinessObjects.Models.FK__Medico_Pa__codig__29572725", "Medico_Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Medico_Paciente)("SH.BusinessObjects.Models.FK__Medico_Pa__codig__29572725", "Medico_Paciente", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "Diagnostico_Medico", "Diagnostico")>
         Public Property Diagnostico() As EntityCollection(Of Diagnostico)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Diagnostico)("SH.BusinessObjects.Models.Diagnostico_Medico", "Diagnostico")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Diagnostico)("SH.BusinessObjects.Models.Diagnostico_Medico", "Diagnostico", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Medico_Paciente")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Medico_Paciente
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Medico_Paciente.
        ''' </summary>
        ''' <param name="codigoMedico">Valor inicial de la propiedad codigoMedico.</param>
        ''' <param name="dPI">Valor inicial de la propiedad DPI.</param>
        ''' <param name="fecha">Valor inicial de la propiedad fecha.</param>
        Public Shared Function CreateMedico_Paciente(codigoMedico As Global.System.Int32, dPI As Global.System.Int32, fecha As Global.System.DateTime) As Medico_Paciente
            Dim medico_Paciente as Medico_Paciente = New Medico_Paciente
            medico_Paciente.codigoMedico = codigoMedico
            medico_Paciente.DPI = dPI
            medico_Paciente.fecha = fecha
            Return medico_Paciente
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property codigoMedico() As Global.System.Int32
            Get
                Return _codigoMedico
            End Get
            Set
                If (_codigoMedico <> Value) Then
                    OncodigoMedicoChanging(value)
                    ReportPropertyChanging("codigoMedico")
                    _codigoMedico = StructuralObject.SetValidValue(value, "codigoMedico")
                    ReportPropertyChanged("codigoMedico")
                    OncodigoMedicoChanged()
                End If
            End Set
        End Property
    
        Private _codigoMedico As Global.System.Int32
        Private Partial Sub OncodigoMedicoChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OncodigoMedicoChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property DPI() As Global.System.Int32
            Get
                Return _DPI
            End Get
            Set
                If (_DPI <> Value) Then
                    OnDPIChanging(value)
                    ReportPropertyChanging("DPI")
                    _DPI = StructuralObject.SetValidValue(value, "DPI")
                    ReportPropertyChanged("DPI")
                    OnDPIChanged()
                End If
            End Set
        End Property
    
        Private _DPI As Global.System.Int32
        Private Partial Sub OnDPIChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnDPIChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property fecha() As Global.System.DateTime
            Get
                Return _fecha
            End Get
            Set
                OnfechaChanging(value)
                ReportPropertyChanging("fecha")
                _fecha = StructuralObject.SetValidValue(value, "fecha")
                ReportPropertyChanged("fecha")
                OnfechaChanged()
            End Set
        End Property
    
        Private _fecha As Global.System.DateTime
        Private Partial Sub OnfechaChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnfechaChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Medico_Pa__codig__29572725", "Medico")>
        Public Property Medico() As Medico
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Medico)("SH.BusinessObjects.Models.FK__Medico_Pa__codig__29572725", "Medico").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Medico)("SH.BusinessObjects.Models.FK__Medico_Pa__codig__29572725", "Medico").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property MedicoReference() As EntityReference(Of Medico)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Medico)("SH.BusinessObjects.Models.FK__Medico_Pa__codig__29572725", "Medico")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Medico)("SH.BusinessObjects.Models.FK__Medico_Pa__codig__29572725", "Medico", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Medico_Paci__DPI__2A4B4B5E", "Paciente")>
        Public Property Paciente() As Paciente
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Medico_Paci__DPI__2A4B4B5E", "Paciente").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Medico_Paci__DPI__2A4B4B5E", "Paciente").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property PacienteReference() As EntityReference(Of Paciente)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Medico_Paci__DPI__2A4B4B5E", "Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__Medico_Paci__DPI__2A4B4B5E", "Paciente", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Paciente")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Paciente
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Paciente.
        ''' </summary>
        ''' <param name="dPI">Valor inicial de la propiedad DPI.</param>
        ''' <param name="noIGSS">Valor inicial de la propiedad noIGSS.</param>
        ''' <param name="nombre">Valor inicial de la propiedad nombre.</param>
        ''' <param name="apellido">Valor inicial de la propiedad apellido.</param>
        ''' <param name="fechaNacimiento">Valor inicial de la propiedad fechaNacimiento.</param>
        Public Shared Function CreatePaciente(dPI As Global.System.Int32, noIGSS As Global.System.Int32, nombre As Global.System.String, apellido As Global.System.String, fechaNacimiento As Global.System.DateTime) As Paciente
            Dim paciente as Paciente = New Paciente
            paciente.DPI = dPI
            paciente.noIGSS = noIGSS
            paciente.nombre = nombre
            paciente.apellido = apellido
            paciente.fechaNacimiento = fechaNacimiento
            Return paciente
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property DPI() As Global.System.Int32
            Get
                Return _DPI
            End Get
            Set
                If (_DPI <> Value) Then
                    OnDPIChanging(value)
                    ReportPropertyChanging("DPI")
                    _DPI = StructuralObject.SetValidValue(value, "DPI")
                    ReportPropertyChanged("DPI")
                    OnDPIChanged()
                End If
            End Set
        End Property
    
        Private _DPI As Global.System.Int32
        Private Partial Sub OnDPIChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnDPIChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noIGSS() As Global.System.Int32
            Get
                Return _noIGSS
            End Get
            Set
                OnnoIGSSChanging(value)
                ReportPropertyChanging("noIGSS")
                _noIGSS = StructuralObject.SetValidValue(value, "noIGSS")
                ReportPropertyChanged("noIGSS")
                OnnoIGSSChanged()
            End Set
        End Property
    
        Private _noIGSS As Global.System.Int32
        Private Partial Sub OnnoIGSSChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoIGSSChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nombre() As Global.System.String
            Get
                Return _nombre
            End Get
            Set
                OnnombreChanging(value)
                ReportPropertyChanging("nombre")
                _nombre = StructuralObject.SetValidValue(value, false, "nombre")
                ReportPropertyChanged("nombre")
                OnnombreChanged()
            End Set
        End Property
    
        Private _nombre As Global.System.String
        Private Partial Sub OnnombreChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnombreChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property apellido() As Global.System.String
            Get
                Return _apellido
            End Get
            Set
                OnapellidoChanging(value)
                ReportPropertyChanging("apellido")
                _apellido = StructuralObject.SetValidValue(value, false, "apellido")
                ReportPropertyChanged("apellido")
                OnapellidoChanged()
            End Set
        End Property
    
        Private _apellido As Global.System.String
        Private Partial Sub OnapellidoChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnapellidoChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property fechaNacimiento() As Global.System.DateTime
            Get
                Return _fechaNacimiento
            End Get
            Set
                OnfechaNacimientoChanging(value)
                ReportPropertyChanging("fechaNacimiento")
                _fechaNacimiento = StructuralObject.SetValidValue(value, "fechaNacimiento")
                ReportPropertyChanged("fechaNacimiento")
                OnfechaNacimientoChanged()
            End Set
        End Property
    
        Private _fechaNacimiento As Global.System.DateTime
        Private Partial Sub OnfechaNacimientoChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnfechaNacimientoChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Cama_Pacien__DPI__1FCDBCEB", "Cama_Paciente")>
         Public Property Cama_Paciente() As EntityCollection(Of Cama_Paciente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Cama_Paciente)("SH.BusinessObjects.Models.FK__Cama_Pacien__DPI__1FCDBCEB", "Cama_Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Cama_Paciente)("SH.BusinessObjects.Models.FK__Cama_Pacien__DPI__1FCDBCEB", "Cama_Paciente", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Diagnostico__DPI__25869641", "Diagnostico_Paciente")>
         Public Property Diagnostico_Paciente() As EntityCollection(Of Diagnostico_Paciente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Diagnostico_Paciente)("SH.BusinessObjects.Models.FK__Diagnostico__DPI__25869641", "Diagnostico_Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Diagnostico_Paciente)("SH.BusinessObjects.Models.FK__Diagnostico__DPI__25869641", "Diagnostico_Paciente", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Medico_Paci__DPI__2A4B4B5E", "Medico_Paciente")>
         Public Property Medico_Paciente() As EntityCollection(Of Medico_Paciente)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Medico_Paciente)("SH.BusinessObjects.Models.FK__Medico_Paci__DPI__2A4B4B5E", "Medico_Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Medico_Paciente)("SH.BusinessObjects.Models.FK__Medico_Paci__DPI__2A4B4B5E", "Medico_Paciente", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__TarjetaVisi__DPI__22AA2996", "TarjetaVisita")>
         Public Property TarjetaVisita() As EntityCollection(Of TarjetaVisita)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of TarjetaVisita)("SH.BusinessObjects.Models.FK__TarjetaVisi__DPI__22AA2996", "TarjetaVisita")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of TarjetaVisita)("SH.BusinessObjects.Models.FK__TarjetaVisi__DPI__22AA2996", "TarjetaVisita", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="Planta")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Planta
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto Planta.
        ''' </summary>
        ''' <param name="idPlanta">Valor inicial de la propiedad idPlanta.</param>
        ''' <param name="nombre">Valor inicial de la propiedad nombre.</param>
        ''' <param name="noCamas">Valor inicial de la propiedad noCamas.</param>
        Public Shared Function CreatePlanta(idPlanta As Global.System.Int32, nombre As Global.System.String, noCamas As Global.System.Int32) As Planta
            Dim planta as Planta = New Planta
            planta.idPlanta = idPlanta
            planta.nombre = nombre
            planta.noCamas = noCamas
            Return planta
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property idPlanta() As Global.System.Int32
            Get
                Return _idPlanta
            End Get
            Set
                If (_idPlanta <> Value) Then
                    OnidPlantaChanging(value)
                    ReportPropertyChanging("idPlanta")
                    _idPlanta = StructuralObject.SetValidValue(value, "idPlanta")
                    ReportPropertyChanged("idPlanta")
                    OnidPlantaChanged()
                End If
            End Set
        End Property
    
        Private _idPlanta As Global.System.Int32
        Private Partial Sub OnidPlantaChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnidPlantaChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property nombre() As Global.System.String
            Get
                Return _nombre
            End Get
            Set
                OnnombreChanging(value)
                ReportPropertyChanging("nombre")
                _nombre = StructuralObject.SetValidValue(value, false, "nombre")
                ReportPropertyChanged("nombre")
                OnnombreChanged()
            End Set
        End Property
    
        Private _nombre As Global.System.String
        Private Partial Sub OnnombreChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnombreChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noCamas() As Global.System.Int32
            Get
                Return _noCamas
            End Get
            Set
                OnnoCamasChanging(value)
                ReportPropertyChanging("noCamas")
                _noCamas = StructuralObject.SetValidValue(value, "noCamas")
                ReportPropertyChanged("noCamas")
                OnnoCamasChanged()
            End Set
        End Property
    
        Private _noCamas As Global.System.Int32
        Private Partial Sub OnnoCamasChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoCamasChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__Cama__idPlanta__1BFD2C07", "Cama")>
         Public Property Cama() As EntityCollection(Of Cama)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Cama)("SH.BusinessObjects.Models.FK__Cama__idPlanta__1BFD2C07", "Cama")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Cama)("SH.BusinessObjects.Models.FK__Cama__idPlanta__1BFD2C07", "Cama", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="SH.BusinessObjects.Models", Name:="TarjetaVisita")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class TarjetaVisita
        Inherits EntityObject
        #Region "Método de generador"
    
        ''' <summary>
        ''' Crear un nuevo objeto TarjetaVisita.
        ''' </summary>
        ''' <param name="noVisita">Valor inicial de la propiedad noVisita.</param>
        ''' <param name="dPI">Valor inicial de la propiedad DPI.</param>
        ''' <param name="horaComienzo">Valor inicial de la propiedad horaComienzo.</param>
        ''' <param name="horaFin">Valor inicial de la propiedad horaFin.</param>
        Public Shared Function CreateTarjetaVisita(noVisita As Global.System.Int32, dPI As Global.System.Int32, horaComienzo As Global.System.DateTime, horaFin As Global.System.DateTime) As TarjetaVisita
            Dim tarjetaVisita as TarjetaVisita = New TarjetaVisita
            tarjetaVisita.noVisita = noVisita
            tarjetaVisita.DPI = dPI
            tarjetaVisita.horaComienzo = horaComienzo
            tarjetaVisita.horaFin = horaFin
            Return tarjetaVisita
        End Function

        #End Region

        #Region "Propiedades simples"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property noVisita() As Global.System.Int32
            Get
                Return _noVisita
            End Get
            Set
                If (_noVisita <> Value) Then
                    OnnoVisitaChanging(value)
                    ReportPropertyChanging("noVisita")
                    _noVisita = StructuralObject.SetValidValue(value, "noVisita")
                    ReportPropertyChanged("noVisita")
                    OnnoVisitaChanged()
                End If
            End Set
        End Property
    
        Private _noVisita As Global.System.Int32
        Private Partial Sub OnnoVisitaChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnnoVisitaChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property DPI() As Global.System.Int32
            Get
                Return _DPI
            End Get
            Set
                OnDPIChanging(value)
                ReportPropertyChanging("DPI")
                _DPI = StructuralObject.SetValidValue(value, "DPI")
                ReportPropertyChanged("DPI")
                OnDPIChanged()
            End Set
        End Property
    
        Private _DPI As Global.System.Int32
        Private Partial Sub OnDPIChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnDPIChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property horaComienzo() As Global.System.DateTime
            Get
                Return _horaComienzo
            End Get
            Set
                OnhoraComienzoChanging(value)
                ReportPropertyChanging("horaComienzo")
                _horaComienzo = StructuralObject.SetValidValue(value, "horaComienzo")
                ReportPropertyChanged("horaComienzo")
                OnhoraComienzoChanged()
            End Set
        End Property
    
        Private _horaComienzo As Global.System.DateTime
        Private Partial Sub OnhoraComienzoChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnhoraComienzoChanged()
        End Sub
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property horaFin() As Global.System.DateTime
            Get
                Return _horaFin
            End Get
            Set
                OnhoraFinChanging(value)
                ReportPropertyChanging("horaFin")
                _horaFin = StructuralObject.SetValidValue(value, "horaFin")
                ReportPropertyChanged("horaFin")
                OnhoraFinChanged()
            End Set
        End Property
    
        Private _horaFin As Global.System.DateTime
        Private Partial Sub OnhoraFinChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnhoraFinChanged()
        End Sub

        #End Region

        #Region "Propiedades de navegación"
    
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("SH.BusinessObjects.Models", "FK__TarjetaVisi__DPI__22AA2996", "Paciente")>
        Public Property Paciente() As Paciente
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__TarjetaVisi__DPI__22AA2996", "Paciente").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__TarjetaVisi__DPI__22AA2996", "Paciente").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No hay documentación de metadatos disponible.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property PacienteReference() As EntityReference(Of Paciente)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__TarjetaVisi__DPI__22AA2996", "Paciente")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Paciente)("SH.BusinessObjects.Models.FK__TarjetaVisi__DPI__22AA2996", "Paciente", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

End Namespace
